kind: List
metadata: {}
apiVersion: v1
items:
- apiVersion: v1
  kind: ReplicationController
  metadata:
    name: oinker-rc
    labels:
      app: oinker
  spec:
    replicas: 3
    selector:
      app: oinker
    template:
      metadata:
        generateName: oinker-pod-
        labels:
          app: oinker
      spec:
        containers:
        - name: server
          image: karlkfi/oinker:shakespeare-k8s
          command:
          - "/bin/bash"
          - "-ceu"
          - "until rake cassandra:setup; do sleep 5; done && rails server"
          ports:
          - name: http
            containerPort: 3000
- apiVersion: v1
  kind: Service
  metadata:
    name: oinker-svc
    labels:
      app: oinker
  spec:
    selector:
      app: oinker
    ports:
    - name: http
      port: 80
      targetPort: http
